name: Villages
description: Create player villages, make regions and start wars.
main: com.domsplace.Villages.VillagesPlugin
author: Dominic
authors: [Dominic, Jordan]
website: http://domsplace.com/
version: '2.23'
load: POSTWORLD
softdepend: [Vault, EssentialsChat]
commands:
   village:
      description: Get Information about Villages and change Village options.
      aliases: [vil, villages]
      usage: /<command>
permissions:
   Villages.*:
     description: Gives access to all Villages permissions.
     default: false
     children:
       Villages.village: true
       Villages.list: true
       Villages.create: true
       Villages.message: true
       Villages.invite: true
       Villages.accept: true
       Villages.deny: true
       Villages.spawn: true
       Villages.leave: true
       Villages.villagetop: true
       Villages.lookup: true
       Villages.border: true
       Villages.map: true
       Villages.admin.*: true
       Villages.mayor.*: true
       Villages.bank.*: true
       Villages.plot.*: true
       Villages.tax.*: true
       Villages.war.*: true
   Villages.village:
     description: Allows access to the Villages command.
     default: true
   Villages.list:
     description: Allows access to view the Villages list.
     default: true
   Villages.create:
     description: Allows access to create a Village.
     default: true
   Villages.message:
     description: Allows a player to send a message to their Village.
     default: true
   Villages.invite:
     description: Allows a player to send an invite for a player to join their Village.
     default: true
   Villages.accept:
     description: Allows a player to accept an invite to a Village.
     default: true
   Villages.deny:
     description: Allows a player to deny an invite to a Village.
     default: true
   Villages.spawn:
     description: Allows a player to go to the Village spawn.
     default: true
   Villages.leave:
     description: Allows a player to leave their Village.
     default: true
   Villages.villagetop:
     description: Allows a player to check the top Villages.
     default: true
   Villages.lookup:
     description: Allows a player to lookup what Village another player belongs to.
     default: true
   Villages.border:
     description: Allows a player to show the Village border.
     default: true
   Villages.map:
     description: Allows a player to view the Village map (Gives a free map item though).
     default: true
   Villages.admin.*:
     description: Allows access to all admin Commands.
     default: false
     children:
       Villages.admin.save: true
       Villages.admin.reload: true
       Villages.admin.command: true
       Villages.admin.delete: true
       Villages.admin.addplayer: true
       Villages.admin.removeplayer: true
       Villages.admin.setmayor: true
       Villages.admin.setname: true
       Villages.admin.setdescription: true
       Villages.admin.override: true
   Villages.admin.save:
     description: Allows access to save all data.
   Villages.admin.reload:
     description: Allows access to reload the data.
   Villages.admin.command:
     description: Allows access to the Village admin command.
   Villages.admin.delete:
     description: Allows access to delete a Village.
   Villages.admin.addplayer:
     description: Allows access to forcibly add a player to a Village.
   Villages.admin.removeplayer:
     description: Allows access to forcibly remove a Player from their Village.
   Villages.admin.setmayor:
     description: Allows access to set the Mayor of a Village.
   Villages.admin.setname:
     description: Allows access to set the name of a Village.
   Villages.admin.setdescription:
     description: Allows access to set the description of a Village.
   Villages.admin.override:
     description: Allows access to bypass all protections.
   Villages.mayor.*:
     description: Allows access to all Mayor Commands
     default: true
     children:
       Villages.mayor.command: true
       Villages.mayor.close: true
       Villages.mayor.kick: true
       Villages.mayor.setdescription: true
       Villages.mayor.setmayor: true
       Villages.mayor.setspawn: true
       Villages.mayor.setname: true
       Villages.mayor.expand: true
       Villages.mayor.shrink: true
       Villages.mayor.explode: true
   Villages.mayor.command:
     description: Allows access to the Village Mayor command.
   Villages.mayor.close:
     description: Allows access for Mayors to close their Village.
   Villages.mayor.kick:
     description: Allows access for Mayors to kick players from their Village.
   Villages.mayor.setdescription:
     description: Allows access for Mayors to set the description of their Village.
   Villages.mayor.setmayor:
     description: Allows access for Mayors to a new Mayor for their Village.
   Villages.mayor.setname:
     description: Allows access for Mayors to set a new name for their Village.
   Villages.mayor.setspawn:
     description: Allows access for Mayors to set the spawn of their Village.
   Villages.mayor.expand:
     description: Allows access for Mayors to expand the area of their Village.
   Villages.mayor.shrink:
     description: Allows access for Mayors to shrink the area of their Village.
   Villages.mayor.explode:
     description: Allows access for Mayors to explode their entire Village.
   Villages.bank.*:
     description: Allows access to all bank commands
     default: true
     children:
       Villages.bank.deposit: true
       Villages.bank.withdraw: true
       Villages.bank.open: true
   Villages.bank.deposit:
     description: Allows access to deposit money into Village bank.
   Villages.bank.withdraw:
     description: Allows access to withdraw money from the Village bank.
   Villages.bank.open:
     description: Allows access to open the Village item bank.
   Villages.plot.*:
     description: Allows access to all plot Commands
     default: true
     children:
       Villages.plot.claim: true
       Villages.plot.check: true
       Villages.plot.set.*: true
   Villages.plot.claim:
     description: Allows access for players to claim plots.
   Villages.plot.check:
     description: Allows access for players to check the claim status of plots.
   Villages.plot.set.*:
     description: Allows access to all plot Set Commands
     children:
       Villages.plot.set.price: true
       Villages.plot.set.owner: true
   Villages.plot.set.price:
     description: Allows access for Mayors to set the price of a plot.
   Villages.plot.set.owner:
     description: Allows access for Mayors to set the owner of a plot.
   Villages.tax.*:
     description: Allows access to all tax commands.
     default: true
     children:
       Villages.tax.check: true
   Villages.tax.check:
     description: Allows access for players to check taxes.
   Villages.war.*:
     description: Allows access to all War commands.
     default: true
     children:
       Villages.war.command: true
   Villages.war.command:
     description: Allows access for players to check war status.